config/routes.rb
Rails.application.routes.draw do
  root "user_sessions#new"
  post "/", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  resources :rooms, only: %i[index show] do
    resources :messages, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :body, presence: true
  validates :reservation_time, presence: true
  validates :done, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  validates :cw_room_name, presence: true
  validates :cw_room_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :email,presence: true, uniqueness: true
  validates :password, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :user_token, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to root_path, danger: "ログインしてください"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  require 'uri'
  require 'net/http'

  def create
    body_params = {
      self_unread: 0,
      body: params[:body]
    }
    @room = Room.find(params[:room_id])
    url = URI("https://api.chatwork.com/v2/rooms/#{@room.cw_room_id}/messages")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(url)
    request["accept"] = 'application/json'
    request["content-type"] = 'application/x-www-form-urlencoded'
    request["x-chatworktoken"] = current_user.user_token
    request.body = URI.encode_www_form(body_params)
    response = http.request(request)
    redirect_to rooms_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  require 'uri'
  require 'net/http'

  def index
    current_user.rooms.destroy_all
    url = URI("https://api.chatwork.com/v2/rooms")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["x-chatworktoken"] = current_user.user_token
    response = http.request(request)
    rooms_data = JSON.parse(response.body)
    rooms_data.each do |room_data|
      room = Room.create(
        user_id: current_user.id,
        cw_room_name: room_data["name"],
        cw_room_id: room_data["room_id"]
      )
    end
    @rooms = current_user.rooms.all
  end

  def show
    @room = Room.find(params[:id])
    url = URI("https://api.chatwork.com/v2/rooms/#{@room.cw_room_id}/members")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    request = Net::HTTP::Get.new(url)
    request["accept"] = 'application/json'
    request["x-chatworktoken"] = current_user.user_token
    response = http.request(request)
    @members = JSON.parse(response.body)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[create new]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to rooms_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title CwApp
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    - if logged_in?
      | ログインしています
    - else
      | ログインしていません
    = yield
    = link_to(t('defaults.logout'), logout_path, data: { turbo_method: :delete, "turbo-confirm" => (t 'defaults.logout?') }, class: "btn btn-primary text-white my-1")

app/views/rooms/index.html.slim
.container.mx-auto
  .flex.flex-wrap.justify-center.pb-20
    - if @rooms.present?
      ul
        - @rooms.each do |room|
          li
          .link
          = link_to room.cw_room_name, room_path(room)
    - else
      p.text-4xl.pt-20 = t('.no_result')

app/views/rooms/show.html.slim
.container.mx-auto
  .flex.justify-center.text-center.main_image
    div
      h1.text-4xl.py-20 = t('.new_message')
      - if @members.present?
        ul
          - @members.each do |member|
            li
            = member['name']
      = form_with model: @message, url: room_messages_path(@room), local: true do |f|
        div.mb-10.text-2xl
          = f.label :body, t('.message_body')
          = f.text_area :body, class: 'input input-bordered input-primary w-full'
        div.actions.mb-20
          = f.submit t('.create_message'), class: 'btn btn-primary text-white'
      = link_to t('.back_to_room'), room_path(@room), class: 'btn btn-secondary text-white mt-5'

app/views/user_sessions/new.html.slim
.flex.justify-center.text-center.main_image
  div
    h1.text-4xl.py-20 = t('.title')
    = form_with model: @user, local: true do |f|
      div.mb-10.text-2xl
        = f.label :email, User.human_attribute_name(:email)
        = f.email_field :email, class: 'input input-bordered input-primary w-full'
      div.mb-10.text-2xl
        = f.label :password, User.human_attribute_name(:password)
        = f.password_field :password, class: 'input input-bordered input-primary w-full'
      div.actions.mb-20
        = f.submit t('defaults.login'), class: 'btn btn-primary text-white'